### PR TITLE
Correct one inaccurate Q&A data point "How can I contribute to Spark?"

### PR DESCRIPTION
**Pull request by alexanderwu-db**
Noticed a data point in the dataset that isn't really natural

### CODE REVIEW

**Comment by srowen** [comment]
I'm not sure if we're going to edit the dataset unless it contains harmful or sensitive info (shouldn't!) or obvious content problems. In a way we want to capture the variations of natural language here, and I find the original question just fine?

**Comment by alexanderwu-db** [comment]
> I'm not sure if we're going to edit the dataset unless it contains harmful or sensitive info (shouldn't!) or obvious content problems. In a way we want to capture the variations of natural language here, and I find the original question just fine?

I'm pretty sure it's a typo. Answering "How can I do X" with "Yes" doesn't seem like something a human would say to me

**Comment by srowen** [comment]
oh yeah fair, but I'll leave it to maintainers to decide policies on typos like that

**Comment by srowen** [comment]
@matthayes is going to collect this feedback and get it into a larger batch update, thank you

**Pull request closed without merging**
