### PR TITLE
Support for Training the Model Using Local Files

### PR DESCRIPTION
**Pull request by xuanyuanking**
Add the support for training the model using local files.

- Modified the train_dolly notebook with new widgets for setting file name, file type
- Only support the local file uploaded in `data` directory.
- Added doc in data readme.

image

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
I don't think this is necessary. datasets.load_dataset will already read those formats, so you can just supply the path as-is to the training script

**Comment by xuanyuanking** [comment]
Seems like reading local files requires different parameters. Therefore, the crucial modification lies in this line of code (https://github.com/databrickslabs/dolly/pull/163/files#diff-954dd14ef412b32269b793ab4a9bf00f8e31f6166d8b06f81bea7d399eb292afR96).

Without this change, I encountered the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File <command-2272171370899772>:2
      1 # Cache data and tokenizer locally before creating a bunch of deepspeed processes and make sure they succeeds.
----> 2 load_training_dataset()
      3 load_tokenizer()

File /Workspace/Repos/yuanjian.li@databricks.com/test/training/trainer.py:90, in load_training_dataset(path_or_dataset)
     88 def load_training_dataset(path_or_dataset: str = DEFAULT_TRAINING_DATASET) -> Dataset:
     89     logger.info(f"Loading dataset from {path_or_dataset}")
---> 90     dataset = load_dataset(path_or_dataset)["train"]
     91     logger.info("Found %d rows", dataset.num_rows)
     93     def _add_text(rec):

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-8b7aaf50-73c2-4810-be9a-90b263320390/lib/python3.9/site-packages/datasets/load.py:1773, in load_dataset(path, name, data_dir, data_files, split, cache_dir, features, download_config, download_mode, verification_mode, ignore_verifications, keep_in_memory, save_infos, revision, use_auth_token, task, streaming, num_proc, storage_options, **config_kwargs)
   1768 verification_mode = VerificationMode(
   1769     (verification_mode or VerificationMode.BASIC_CHECKS) if not save_infos else VerificationMode.ALL_CHECKS
   1770 )
   1772 # Create a dataset builder
-> 1773 builder_instance = load_dataset_builder(
   1774     path=path,
   1775     name=name,
   1776     data_dir=data_dir,
   1777     data_files=data_files,
   1778     cache_dir=cache_dir,
   1779     features=features,
   1780     download_config=download_config,
   1781     download_mode=download_mode,
   1782     revision=revision,
   1783     use_auth_token=use_auth_token,
   1784     storage_options=storage_options,
   1785     **config_kwargs,
   1786 )
   1788 # Return iterable dataset in case of streaming
   1789 if streaming:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-8b7aaf50-73c2-4810-be9a-90b263320390/lib/python3.9/site-packages/datasets/load.py:1502, in load_dataset_builder(path, name, data_dir, data_files, cache_dir, features, download_config, download_mode, revision, use_auth_token, storage_options, **config_kwargs)
   1500     download_config = download_config.copy() if download_config else DownloadConfig()
   1501     download_config.use_auth_token = use_auth_token
-> 1502 dataset_module = dataset_module_factory(
   1503     path,
   1504     revision=revision,
   1505     download_config=download_config,
   1506     download_mode=download_mode,
   1507     data_dir=data_dir,
   1508     data_files=data_files,
   1509 )
   1511 # Get dataset builder class from the processing script
   1512 builder_cls = import_main_class(dataset_module.module_path)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-8b7aaf50-73c2-4810-be9a-90b263320390/lib/python3.9/site-packages/datasets/load.py:1109, in dataset_module_factory(path, revision, download_config, download_mode, dynamic_modules_path, data_dir, data_files, **download_kwargs)
   1106 download_config.force_extract = True
   1107 download_config.force_download = download_mode == DownloadMode.FORCE_REDOWNLOAD
-> 1109 filename = list(filter(lambda x: x, path.replace(os.sep, "/").split("/")))[-1]
   1110 if not filename.endswith(".py"):
   1111     filename = filename + ".py"

TypeError: replace() takes 2 positional arguments but 3 were given
```

log:
```
2023-05-15 20:24:23 INFO [training.trainer] Loading dataset from /Workspace/Repos/yuanjian.li@databricks.com/test/data/incident_summary_cleaned_by_dolly.jsonl
```

**Comment by srowen** [comment]
You need to pass the parent dir, not file path

**Comment by xuanyuanking** [comment]
em... I got the same type error after changing to the parent dir.

**Comment by srowen** [comment]
Let's see your modification to trainer.py

**Comment by xuanyuanking** [comment]
Close this.
Confirmed with @srowen that we can support the local files by passing the `dir` string to `load_training_dataset`.

**Pull request closed without merging**
