### PR TITLE
i have recorded a very high quality tutorial please accept this change

### PR DESCRIPTION
**Pull request by FurkanGozukara**
Thank you so much for the model. Added link to readme into proper section with a proper description.

### CODE REVIEW

**Comment by srowen** [comment]
OK thank you though I have some concerns about what you suggest. For example you don't need to download the model by hand. Just let HF download it. 
You also don't need gradio to avoid redownloading the model. It does not reinitialize every time you use the pipeline.
Whether you need 8bit depends on your hardware.
You don't need to install bitsandbytes from git, just install the normal pypi version.

Etc. These are minor, just not sure if they're the simplest instructions for using this. There is already usage info, and maybe we can add a few notes as needed to existing docs instead.

**Comment by FurkanGozukara** [comment]
> OK thank you though I have some concerns about what you suggest. For example you don't need to download the model by hand. Just let HF download it. You also don't need gradio to avoid redownloading the model. It does not reinitialize every time you use the pipeline. Whether you need 8bit depends on your hardware. You don't need to install bitsandbytes from git, just install the normal pypi version.
> 
> Etc. These are minor, just not sure if they're the simplest instructions for using this. There is already usage info, and maybe we can add a few notes as needed to existing docs instead.

1 : ye i explained that. but this way you can download into the drive and folder you wish. believe me so many people asks where is files downloaded

2 : i tried to meant that if you use the code given on site as example on your page, it will reload model into vram. gradio avoids that

3 : correct. but i had to spend quite a bit time to make it work

4 : nope here you are wrong. it is not working on windows.

**Comment by srowen** [comment]
Thank you, though there are many videos and resources about Dolly now, so I don't think we're going to list some on the project sites.

**Comment by Anthropora** [comment]
> > OK thank you though I have some concerns about what you suggest. For example you don't need to download the model by hand. Just let HF download it. You also don't need gradio to avoid redownloading the model. It does not reinitialize every time you use the pipeline. Whether you need 8bit depends on your hardware. You don't need to install bitsandbytes from git, just install the normal pypi version.
> > Etc. These are minor, just not sure if they're the simplest instructions for using this. There is already usage info, and maybe we can add a few notes as needed to existing docs instead.
> 
> 1 : ye i explained that. but this way you can download into the drive and folder you wish. believe me so many people asks where is files downloaded
> 
> 2 : i tried to meant that if you use the code given on site as example on your page, it will reload model into vram. gradio avoids that
> 
> 3 : correct. but i had to spend quite a bit time to make it work
> 
> 4 : nope here you are wrong. it is not working on windows.

Yeah, I haven't been able to get it to work on Windows OS at all. I have to use Google Collab to use it.

**Pull request closed without merging**
